baseURL = "https://fontikar.com/"
languageCode = "en-us"
title = "Fonti Kar"
theme = "ananke"

[params]
  favicon = ""
  site_logo = ""
  description = "Dr. Fonti Kar does cool science!"
  facebook = ""
  twitter = "https://twitter.com/fonti_kar"
  instagram = ""
  youtube = ""
  github = "https://github.com/fontikar"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  featured_image = "/images/fancy-swirly-rocks.jpg"
  recent_posts_number = 2

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = -110
